# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "CI pipeline"

  lane :ci do
    run_tests(
      scheme: "RideTogether",
      devices: ["iPhone 16"]
    )

    build_app(
      workspace: "RideTogether.xcworkspace",
      scheme: "RideTogether",
      skip_codesigning: true
    )
  end
end