# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

# Suppress the warning about unused master specs repo
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'RideTogether' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RideTogether
  pod 'SwiftLint'
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/Core'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift'
  pod 'FirebaseStorage'
  pod 'FirebaseStorage'
  pod 'Firebase/Auth'
  pod 'MJRefresh'
  pod 'MASegmentedControl'
  pod 'Kingfisher'
  pod 'CoreGPX'
  pod 'DGCharts'
  pod 'RSKPlaceholderTextView'
  pod 'lottie-ios'
  pod 'JGProgressHUD'
  pod 'Firebase/Crashlytics'
end

post_install do |installer|   
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
