platform :ios, '15.0'

target 'RideTogether' do
  use_frameworks!

  pod 'SwiftLint'
  pod 'IQKeyboardManagerSwift'
  pod 'MJRefresh'
  pod 'MASegmentedControl'
  pod 'Kingfisher', '~> 7.11.0'
  pod 'CoreGPX'
  pod 'Charts', '~> 4.1.0'
  pod 'RSKPlaceholderTextView'
  pod 'lottie-ios'
  pod 'JGProgressHUD'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['OTHER_CFLAGS'] = '$(inherited) -Wno-strict-prototypes'
    end
  end
end